// Generated by CoffeeScript 1.6.3
(function() {
  var fs, host_parser;

  fs = require('fs');

  host_parser = require("./hosts_parser");

  fs.readFile('/etc/hosts', 'utf8', function(err, data) {
    var i, _i, _len, _ref;
    host_parser.parser.parse(data);
    _ref = host_parser.hosts;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      console.log(i);
    }
    return console.log(host_parser.groups);
  });

}).call(this);
